resources:
- name: pal-stocks
  type: git
  source:
    uri: https://github.com/sanjeevimohan/pal-stocks
    branch: master

- name: deploy-pal-stocks
  type: cf
  source:
    api: https://api.system.cumuluslabs.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: msanjeevi-pal
    space: sandbox
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: pal-stocks
    trigger: true
  - task: test
    file: pal-stocks/ci/tasks/test.yml

- name: build
  public: true
  plan:
  - get: pal-stocks
    trigger: true
    passed: [test]
  - task: package
    file: pal-stocks/ci/tasks/package.yml
  - put: deploy-pal-stocks
    params:
      manifest: pal-stocks/manifest.yml
      path: package-output/pal-stocks.war

- name: build-uat
  public: true
  plan:
  - get: pal-stocks
    trigger: false
    passed: [build]
  - task: package
    file: pal-stocks/ci/tasks/package.yml
  - put: deploy-pal-stocks
    params:
      manifest: pal-stocks/manifest-uat.yml
      path: package-output/pal-stocks.war